application_sonata_user_user:
    resource: "@ApplicationSonataUserBundle/Controller/UserController.php"
    type:     annotation

application_sonata_user_group:
    resource: "@ApplicationSonataUserBundle/Controller/GroupController.php"
    type:     annotation

administration_category:
    resource: "@AdministrationBundle/Controller/CategoryController.php"
    type:     annotation

administration_famille:
    resource: "@AdministrationBundle/Controller/FamilleController.php"
    type:     annotation

administration_produit:
    resource: "@AdministrationBundle/Controller/ProduitController.php"
    type:     annotation

administration_cart:
    resource: "@AdministrationBundle/Controller/cartController.php"
    type:     annotation

application_sonata_user_user:
    resource: "@ApplicationSonataUserBundle/Controller/UserController.php"
    type:     annotation



site:
    resource: "@SiteBundle/Resources/config/routing.yml"
    prefix:   /

administration:
    resource: "@AdministrationBundle/Resources/config/routing.yml"
    prefix:   /administration
    
sonata_user:
    resource: '@SonataUserBundle/Resources/config/routing/admin_security.xml'
    prefix: /administration
    
sonata_user_admin_resetting:
    resource: '@SonataUserBundle/Resources/config/routing/admin_resetting.xml'
    prefix: /resetting    
 
admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /administration
    
#admin_login:
#    pattern:  /admin/login
#    defaults: { _controller: FOSUserBundle:Security:login }
#
#admin_login_check:
#    pattern:  /admin/login_check
#    defaults: { _controller: FOSUserBundle:Security:check }
#
#admin_logout:
#    pattern:  /admin/logout
#    defaults: { _controller: FOSUserBundle:Security:logout }





fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"
    prefix: admin
    
fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile
  
fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register
  
fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting
  
fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /change-password
  
  
#sonata_user_security:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_security_1.xml"
#
#sonata_user_resetting:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_resetting_1.xml"
#    prefix: /resetting
#
#sonata_user_profile:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_profile_1.xml"
#    prefix: /profile
#
#sonata_user_register:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_registration_1.xml"
#    prefix: /register
#
#sonata_user_change_password:
#    resource: "@SonataUserBundle/Resources/config/routing/sonata_change_password_1.xml"
#    prefix: /profile
    
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /administration