
security:
    role_hierarchy:
        ROLE_ADMIN:       [ROLE_USER, ROLE_SONATA_ADMIN]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        SONATA:
            - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT
        ROLE_EDIT_USER:
            - ROLE_SONATA_ADMIN_USER_LIST
            - ROLE_SONATA_ADMIN_USER_EDIT    
    access_control:
        
         - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/logout$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/login_check$, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/admin/, roles: ROLE_SUPER_ADMIN }
         - { path: ^/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/profile, role: IS_AUTHENTICATED_FULLY }
         - { path: ^/deconnexion$, role: IS_AUTHENTICATED_FULLY }
         - { path: ^/_wdt, role: IS_AUTHENTICATED_ANONYMOUSLY }
         - { path: ^/_profiler, role: IS_AUTHENTICATED_ANONYMOUSLY }
         
    providers:
        fos_userbundle:
            id: fos_user.user_manager
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:            ^/administration/
            context:            user
            provider:   in_memory
            form_login:
                provider:       fos_userbundle
                login_path:     /administration/login
                use_forward:    false
                #use_referer: true
                check_path:     /administration/login_check
                failure_path:   null
                csrf_provider:  form.csrf_provider
                default_target_path: /administration/dashboard
            #logout:         true
            logout:
               path:           /administration/logout
               target:          /administration/login
            anonymous:    true
        main:
            anonymous: ~
            pattern:             .*
            context:             user
            switch_user: true
            form_login:
                provider:       fos_userbundle
                login_path:     /login 
                use_forward:    false
                check_path:     /login_check
                failure_path:   null
                csrf_provider:  form.csrf_provider
                default_target_path: /profile/
            #logout:         true
            logout:
                path:           fos_user_security_logout
                target:         /login
            anonymous:      true
        login:

            pattern:  admin/login
            security: false
        
      
            
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    acl:
        connection: default