<?php

/**
 * This file is part of the <name> project.
 *
 * (c) <yourname> <youremail>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Application\Sonata\UserBundle\Entity;

use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use AdministrationBundle\Entity\cart;
use Doctrine\Common\Collections\ArrayCollection;
/**
 * This file has been generated by the Sonata EasyExtends bundle.
 *
 * @link https://sonata-project.org/bundles/easy-extends
 *
 * References :
 *   working with object : http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 *
 * @author <yourname> <youremail>
 */
class User extends BaseUser
{
    /**
     * @var int $id
     */
    protected $id;



    /** @var ArrayCollection $carts
     *
     *
     * @ORM\OneToMany(targetEntity="AdministrationBundle\Entity\cart", mappedBy="customer", cascade={"persist","remove"})
     *
     */

    protected $carts;

    /**
     * Get id
     *
     * @return int $id
     */
    public function getId()
    {
        return $this->id;
    }


    /**
     * @param cart $cart
     * @return User
     *
     */


    public function addcart(cart $cart)
    {
        $cart->setCustomer($this);
        $this->carts[] = $cart;
        return $this;
    }


    /**
     * @return ArrayCollection
     */
    public function getcarts(){

        return $this->carts;

    }



}
