administration_homepage:
    path:     /login
    defaults: { _controller: AdministrationBundle:AdminSecurity:login }
    
administration_login_checkAction:
    path:     /login_check
    defaults: { _controller: AdministrationBundle:AdminSecurity:check }
    
administration_login_logout:
    path:     /logout
    defaults: { _controller: AdministrationBundle:AdminSecurity:logout }

administration_dashboard:
    path:     /dashboard
    defaults: { _controller: AdministrationBundle:Core:dashboard }

administration_famille:
    path:     /familles
    defaults: { _controller: AdministrationBundle:Famille:index }

administration_produits:
    path:     /produits
    defaults: { _controller: AdministrationBundle:Produit:index }