administration_homepage:
    path:     /login
    defaults: { _controller: AdministrationBundle:AdminSecurity:login }
    
administration_login_checkAction:
    path:     /login_check
    defaults: { _controller: AdministrationBundle:AdminSecurity:check }
    
administration_login_logout:
    path:     /logout
    defaults: { _controller: AdministrationBundle:AdminSecurity:logout }

administration_dashboard:
    path:     /dashboard
    defaults: { _controller: AdministrationBundle:Core:dashboard }


administration_carts:
    resource: "@AdministrationBundle/Resources/config/routing/cart.yml"
    prefix:   /

administration_cartfids:
    resource: "@AdministrationBundle/Resources/config/routing/cartfid.yml"
    prefix:   /

administration_categories:
    resource: "@AdministrationBundle/Resources/config/routing/category.yml"
    prefix:   /

administration_familles:
    resource: "@AdministrationBundle/Resources/config/routing/famille.yml"
    prefix:   /

administration_produits:
    resource: "@AdministrationBundle/Resources/config/routing/produit.yml"
    prefix:   /
