<?php

namespace AdministrationBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CartfidRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CartfidRepository extends EntityRepository
{
}
